description: build libretro


inputs:
  token:
    description: github token
    required: false
    default: ''

  arch:
    description: system platform
    required: false
    default: x64


runs:
  using: composite

  steps:
    - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
      with:
        token: ${{ inputs.token }}
        branch: upstream
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@mingw-install
      with:
        arch: ${{ inputs.arch }}


    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ inputs.arch }}


    - shell: bash
      run: |
        merge () {
          echo "<<< ===  merging  $1  === >>>"
          git merge origin/$1
          echo ""
        }

        merge blip_fast
        merge epsm_remove
        merge framebuffer_resize
        merge inline_speed
        merge loadstate_mismatch
        merge mingw_flags

        # merge libretro-options
        # merge crop-border
        # merge fast-bootrom
        # merge osd-message
        # merge sprite-limit
        # merge video-overclock
        # merge volume-level


    - shell: bash
      run: |
        make libretro MESENPLATFORM="${{ inputs.arch }}" USE_GCC="true" LTO="true" STATICLINK="true" CPPC="ccache $MINGW_CXX" CC="ccache $MINGW_CC" CXX="ccache $MINGW_CXX"


    - uses: actions/upload-artifact@main
      with:
        name: mesen_${{ inputs.arch }}
        path: ${{ github.workspace }}/bin/**.dll
